#!/bin/bash

_capture_dir="$HOME/tmp/screenshots"
_scrot_filename="$(hostname)_%Y-%m-%d-%T_\$wx\$h.png"
_scrot_cmd="xdotool key \"Ctrl+F9\" && \
            mv \$f $HOME/tmp/screenshots/ \
            && google picasa post 'Screenshots' \
            $HOME/tmp/screenshots/\$f && rm $HOME/tmp/screenshots/\$f"
case $1 in
    start) xdotool key "Shift+F9" "F9" ;;
    finish) [[ ! -d "$_capture_dir" ]] && mkdir -p "$_capture_dir"; scrot "$_scrot_filename" -e "$_scrot_cmd" ;;
esac
