#!/bin/bash

case $1 in

    startup) sleep 0.25; notes="233.08 261.63 207.65 103.83 155.56" delay=100 length=150 ;;

    shutdown) notes="196.00 220.00 174.61 87.31 130.81" delay=100 length=150 ;;

    sleep) notes="$(echo $(seq 2500 -50 800))" delay=0 length=15 ;;
    resume) notes="$(echo $(seq 800 50 2500))" delay=0 length=15 ;;


esac

#for note in $notes; do sudo beep -f $note -l $length -D $delay; done; sleep 1;
for note in $notes; do sudo beep -f $note -l $length ; done; sleep 1;
