#!/bin/bash

# library of common functions for utility scripts
# es@ethanschoonover.com

# ----------------------------------------------------------------------
# Script Settings & Globals
# ----------------------------------------------------------------------

set -o errexit
set -o nounset
trap Trap EXIT INT TERM

STATEFILE="/var/tmp/$(basename "$0")"
SCRIPT_COMPLETE=false
INITIAL_ARGS="$*"

# whether to automatically generate a dbus notification of success
QUIET_SUCCESS=${QUIET_SUCCESS:-true}

# whether script failure should be silent (no failure dbus notification)
QUIET_FAILURE=${QUIET_FAILURE:-false}

DEBUG=${DEBUG:-false} # default if not set in main script

# ----------------------------------------------------------------------
# Functions
# ----------------------------------------------------------------------
# Don't change state, return values
# Avoid using globals opaquely (echo results)
#
# This_Is_A_Global_Function
# _This_Is_A_Local_Function
# THIS_IS_A_GLOBAL_VARIABLE
# _THIS_IS_A_FUNCTION_LOCAL_STATE_VARIABLE (a global used only in 1 func)
# _this_is_a_local_temp_variable

Flash () { As_User "notify-send -u low        \"$*\""; }
Alert ()  { As_User "notify-send -u normal     \"$*\""; }
Warn ()   { As_User "notify-send -u critical   \"$*\""; }

Set_Initial_Args () { INITIAL_ARGS="$*"; }
Get_Initial_Args () { echo "${INITIAL_ARGS:-}"; }

Is_Root ()
{
    [[ "$(whoami)" == "root" || "$USER" == "root" || -z "$USER" ]]
}

Fail ()
{
    FAILURE="$*"
    echo "$*" && exit 1
}

Trap ()
{
TEST="$?"
    if [ "$TEST" -eq 0 ]; then
        ${QUIET_SUCCESS:-false} || Flash "$(basename $0) $INITIAL_ARGS"
    elif ! ${QUIET_FAILURE:-false}; then
        Warn "$TEST FAILED: $(basename $0) $(Get_Initial_Args)${FAILURE:+ - }${FAILURE:-}"
    fi
}

Debug ()
{
# quick debug function, better info than "caller"
# called without parameters at top of function; reports where it was called 
# from (calling function and line number)
# DEBUG must be set to true in main script for this to trigger
    $DEBUG || return 0;
    [[ ${1:-} ]] \
    && local with_args=" with arguments \"$@\"" \
    || local with_args=""
    echo -n "FUNCTION: ${FUNCNAME[1]:-}() line ${BASH_LINENO[0]} "
    echo "called by ${FUNCNAME[2]:-}${with_args} at line ${BASH_LINENO[1]}"
}

As_User ()
{
    if [ -z "${_AS_USER:-}" ] && Is_Root; then
        for _windowmanager in xmonad xfce bash zsh; # in console uses bash/zsh login
        do _pid=$(pgrep -o $_windowmanager) && break; done
        for _envvar in USER XAUTHORITY DISPLAY DBUS_SESSION_BUS_ADDRESS;
        do eval export $(grep -z ^$_envvar /proc/$_pid/environ); done
        _AS_USER="su $USER -c"
    fi
    ${_AS_USER:-eval} "$*"
}

Set_State ()
{
# takes one argument, the value of the state to be recorded
# will correctly error exit if missing value of STATE
# _Record_State min
    echo -n "$INITIAL_ARGS" > "$STATEFILE"
    chmod a+rw "$STATEFILE"
    if Is_Root; then
        As_User # get correct $USER value
        chown $USER:users "$STATEFILE"
    fi
}

Get_State ()
{
# first check if we have set state variable (used only internally in
# this function) and if not, read state from file. finally return state.
    [[ -z "${STATE:-}" && -e "$STATEFILE" ]] && STATE="$(cat $STATEFILE)" || true
    echo "${STATE:-}" # this may legitimately be null
}

Remove_State ()
{
    if [ -e "$STATEFILE" ]; then rm "$STATEFILE"; fi
}
