#!/bin/bash

# gcal {update|view} {week|month|all}
# cf https://github.com/insanum/gcalcli

# require $DATA_DIR
. $HOME/.profile

CALDIR=$HOME/$DATA_DIR/cal
TIMEPERIOD=$2
CALFILE=cal-$TIMEPERIOD
[ -d "$CALDIR" ] || mkdir -p "$CALDIR"

if ! ping -c 1 -w 2 www.google.com > /dev/null; then
    Warn "gcal: failed to update calendar - offline"
    exit
fi

if [[ "$1" == update && "$2" == "all" ]]; then
    gcal update week
    gcal update month
    exit
fi



case $1 in
    update)
        gcalcli --cal Ethan --cal 'Family Shared' --cal "US Holidays" --width=21 cal${2:0:1} > $CALDIR/$CALFILE.tmp
        if [ $? -eq 0 ]
        then
            flash "gcal - updated $2 calendar"
            [ -e "$CALDIR/$CALFILE" ] && rm $CALDIR/$CALFILE || true
            mv $CALDIR/$CALFILE.tmp $CALDIR/$CALFILE
        else
            warn "gcal: unknown failure to update calendar"
            [ -e "$CALDIR/$CALFILE" ] && rm $CALDIR/$CALFILE.tmp || true
            echo -n "*" >> $CALDIR/$CALFILE
        fi
    ;;
    view)
        cat $CALDIR/$CALFILE
        HOURS_SINCE_UPDATE=$(((`date --utc +%s`-`date --utc --reference=$CALDIR/$CALFILE +%s`)/60/60))
        if [ "$HOURS_SINCE_UPDATE" -gt "1" ]; then
            echo -n "$HOURS_SINCE_UPDATE hours since last update "
        elif [ "$HOURS_SINCE_UPDATE" -gt "0" ]; then
            echo -n "$HOURS_SINCE_UPDATE hour since last update "
        fi
        sleep 30
    ;;
esac




