#!/bin/bash

newlayout="$1"

if [[ -z "$newlayout" ]]; then # no command line value
    case $(setxkbmap -query | grep layout: | awk 'END{print $2}') in
        us) newlayout=gr ;;
        *)  newlayout=us ;;
    esac
fi

case $newlayout in
    gr) setxkbmap -layout "gr" -variant "polytonic" -option ctrl:nocaps ;;
    us) setxkbmap -option ctrl:nocaps -layout "us" ;;
esac

