#!/bin/bash
#
# notify

ROOTMODE=false

ASUSER="eval"
if [[ -z "${USER:-}" || "${USER:-}" == "root" ]]; then
    ROOTMODE=true
    for _windowmanager in xmonad xfce bash zsh; # in console uses bash/zsh login
    do _pid=$(pgrep -o $_windowmanager) && break; done
    for _envvar in USER XAUTHORITY DISPLAY DBUS_SESSION_BUS_ADDRESS;
    do eval export $(grep -z ^$_envvar /proc/$_pid/environ); done
    ASUSER="su $USER -c"
fi

$ASUSER "notify-send -u low \"$*\""
