#!/bin/bash

# set queue location
QUEUE="$HOME/var/queue"
CAL_QUEUE="$QUEUE/calendar"

# confirm we have arguments
if [[ -z "$*" ]]
then
    notify-send "MISSING VALUE: quickcal needs a value to set"
    exit
fi


# check for queue directory
[[ ! -d "$CAL_QUEUE" ]] && mkdir -p "$CAL_QUEUE"

# try to push cal event
_result="$(google calendar add "$1" 2>&1)"
if [[ $? -gt 0 ]]
then
    # dump to file on error
    echo "$1" >> "$CAL_QUEUE/quickcal-$(date +%F-%H%M%S)"
    notify-send "QUICKCAL" "Google calendar not accessible; cal entry queued."
else
    # open browser on success
    _url="$(echo $_result | sed "s/Event created: \(.*\)$/\1/")"
    $BROWSER "$_url"
    notify-send "QUICKCAL" "Google calendar entry created."
fi

