#!/bin/bash
#
# system functions (sleep, boot, etc.)

# ----------------------------------------------------------------------
# Source functions library
# ----------------------------------------------------------------------
# handles both symlinked and original script
# expects function file in same directory as script (or script target)

QUIET_SUCCESS=false
DEBUG=true
functions="$(dirname $(readlink -f $0))/functions"
[ -e "$functions" ] || functions=/usr/bin/functions
. "$functions"

# ----------------------------------------------------------------------
# System Functions
# ----------------------------------------------------------------------

case $1 in

    boot)
        #bloop startup
        sudo wireless all restore
        display auto || true
        power auto
        ;;

    sleep|suspend)
        display darklock || true
        bloop down
        sudo systemctl suspend || true
        display auto || true
        display unlock || true
        power auto
        ;;

    poweroff|off|shutdown)
        bloop shutdown
        power preshutdown
        #sudo rmmod e1000e || true
        if ! sudo rmmod e1000e; then warn "rmmod e1000e failed" && sleep 2; fi
        sudo systemctl stop offlineimap@es.service
        sudo systemctl poweroff || exit 1
        ;;

    reboot|restart)
        bloop shutdown
        power preshutdown
        #sudo rmmod e1000e || true
        if ! sudo rmmod e1000e; then warn "rmmod e1000e failed" && sleep 2; fi
        sudo systemctl stop offlineimap@es.service
        sudo systemctl reboot || exit 1
        ;;

    hibernate)
        # TODO: encrypted swap hibernate support
        exit 1
        ;;

esac
