#!/bin/bash

init_trayer ()
{
# if running, kill it, init either way

    for pid in $(pgrep trayer); do kill -9 $pid; done 

    trayer \
        --edge top \
        --align right \
        --SetDockType true \
        --SetPartialStrut true \
        --expand false \
        --widthtype percent \
        --width 6 \
        --tint 0x073642 \
        --transparent true \
        --alpha 100 \
        --margin 0 \
        --padding 0 \
        --heighttype pixel \
        --height 20 &

}

init_stalonetray () 
{
# if running, move it, else run it

if pgrep stalonetray &>/dev/null; then

    eval "$(xdotool search --classname stalonetray getwindowgeometry --shell $@ | grep WIDTH)"

    YPOS=$(( $(xdpyinfo | grep -m 1 dimensions | sed "s/[^[:digit:]]*\([[:digit:]]*\).*/\1/") - $WIDTH ))

    xdotool search --classname stalonetray windowmove $YPOS 0

else

    stalonetray \
        --dockapp-mode none \
        --background '#073642' \
        --icon-size 16 \
        --slot-size 20 \
        --sticky \
        --window-strut auto \
        --window-type dock \
        --geometry 7x1-1+0 \
        --max-geometry 10x1 \
        --icon-gravity E \
        --grow-gravity W \
        --kludges fix_window_pos,force_icons_size \
        --window-layer bottom &

fi
}

init_stalonetray
