#!/bin/bash

STATEROOT=/var/tmp

touch $STATEROOT/trackpad

case $* in
    toggle)  synclient -l | grep -q 'TouchpadOff.*=.*1' && trackpad on || trackpad off ;;
    on)      synclient TouchpadOff=0; flash "trackpad on"  ;;
    off)     synclient TouchpadOff=1; flash "trackpad off" ;;
    restore)
        [[ -f "$STATEROOT/trackpad" && -n "$(cat "$STATEROOT/trackpad")" ]] && _state=$(cat "$STATEROOT/trackpad") || _state=on
        trackpad $_state
        ;;
esac

