#!/bin/bash

#ALSACTRL=$ALSACTRL
#ALSAINPT="Capture"

ALSACTRL=Speaker
ALSAINPT="Analog In"

# audio mode (pulse/alsa)
command -v pamixer &>/dev/null && ALSA=false || ALSA=true

_adj=1 # used if no value supplied, e.g. volume up OR volume up 10

case $1 in
    up)     CMDALSA="amixer -- set $ALSACTRL ${2:-$_adj}%+ unmute -q || true"
            CMDPULSE="/usr/bin/pamixer --increase $_adj --unmute"
            ;;
    mid)    CMDALSA="amixer -- set $ALSACTRL 75% unmute -q"
            CMDPULSE=""
            ;;
    max)    CMDALSA="amixer -- set $ALSACTRL 100% unmute -q"
            CMDPULSE=""
            ;;
    down)   CMDALSA="amixer -- set $ALSACTRL ${2:-$_adj}%- unmute -q"
            CMDPULSE="/usr/bin/pamixer --decrease $_adj --unmute"
            ;;
    mute)   CMDALSA="amixer -- set $ALSACTRL mute -q"
            CMDPULSE="/usr/bin/pamixer --mute"
            ;;
    unmute) CMDALSA="amixer -- set $ALSACTRL unmute -q"
            CMDPULSE="/usr/bin/pamixer --unmute"
            ;;
    toggle) CMDALSA="amixer set $ALSACTRL toggle -q"
            CMDPULSE="$(/usr/bin/pamixer --get-mute) && volume unmute || volume mute"
            ;;
    mic) 
            case $2 in
            mute)   CMDALSA="amixer set \"$ALSAINPT\" mute -q"
                    CMDPULSE="pamixer set \"$ALSAINPT\"  mute -q"
                    ;;
            unmute) CMDALSA="amixer set \"$ALSAINPT\" unmute -q"
                    CMDPULSE=""
                    ;;
            toggle) CMDALSA="amixer set \"$ALSAINPT\" toggle -q"
                    CMDPULSE=""
                    ;;
            esac
            ;;
esac

if $ALSA && [ -n "$CMDALSA" ]; then eval "$CMDALSA";
elif ! $ALSA && [ -n "$CMDPULSE" ]; then eval "$CMDPULSE"; fi
