#!/bin/bash

STATEROOT=/var/tmp

touch $STATEROOT/wifi
touch $STATEROOT/bluetooth
if [ "$(whoami)" == "root" ]; then
chmod a+rw $STATEROOT/wifi
chmod a+rw $STATEROOT/bluetooth
fi

Notify ()
{
:
}

wifi ()
{
    case $* in
        toggle) sudo rfkill list wifi | egrep -iq "soft.*yes" && wifi off || wifi on ;;
        on) sudo rfkill unblock wifi && ip link set wlan0 up; Notify "wifi on" && echo -n on > $STATEROOT/wifi ;;
        off) sudo rfkill block wifi && Notify "wifi off" && echo -n off > $STATEROOT/wifi ;;
        restore)
            [[ -f "$STATEROOT/wifi" && -n "$(cat "$STATEROOT/wifi")" ]] && _state=$(cat "$STATEROOT/wifi") || _state=on
            wifi $_state
            ;;
    esac
}

bluetooth ()
{
    case $* in
        toggle) sudo /usr/sbin/rfkill list bluetooth | egrep -iq "soft.*yes" && bluetooth on || bluetooth off ;;
        on) sudo /usr/sbin/rfkill unblock bluetooth && echo -n on > $STATEROOT/bluetooth ;;
        off) sudo /usr/sbin/rfkill block bluetooth && echo -n off > $STATEROOT/bluetooth ;;
        restore)
            [[ -f "$STATEROOT/bluetooth" ]] && [[ -n "$(cat "$STATEROOT/bluetooth")" ]] && _state=$(cat "$STATEROOT/bluetooth")
            bluetooth ${_state:-on}
            ;;
    esac
}

# both wifi and bluetooth
all ()
{
    case $* in
        toggle) bluetooth toggle; wifi toggle ;;
        on) bluetooth on; wifi on ;;
        off) bluetooth off; wifi off ;;
        restore) wifi restore; bluetooth restore; ;;
    esac
}

$*
