#!/bin/bash
MODE="$(cat /var/tmp/power | tr [a-z] [A-Z])"
case $MODE in
    MIN) FC=#719e07 BC=#073642 ;;
    MAX) FC=#d33682 BC=#073642 ;;
    MIV) BC=#719e07 FC=#073642 ;;
    MOV) BC=#d33682 FC=#073642 ;;
    *) MCOLOR=#dc322f ;;
esac
echo "<fc=$FC,$BC> ${MODE} </fc>"
